name: Release-plz 'release'
# Release-plz: https://release-plz.dev/docs/github/quickstart#3-setup-the-workflow

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:  # release-package flag
      release-package:
        type: boolean
        description: "Release packages to crates.io"
        default: false

jobs:

  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for release-plz to create tags
      id-token: write # Required for OIDC token exchange
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # https://crates.io/docs/trusted-publishing
      # FIXME: If there is no releases to be published, skip this step.
      #        What is the best way to check this?
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
